version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes: 
      - data:/code/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "15"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

volumes:
  data: