pipeline {
    agent { docker { image 'python:3.9-slim' } }
     environment {
        CI = 'true'
    }
    stages {
        stage('build') {
            steps {
                sh  '''
                  cd app_python
                  pip install --no-cache-dir -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                  pip install pytest
                  pip install pytest-cov
                  pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
                '''
            }
        }
    }
}

