pipeline {
    agent {
      docker {
            image 'python:3.9-alpine3.14'
            args '-p 3000:3000 -p 5000:5000' 
      }
    }
     environment {
        CI = 'true'
    }
    stages {
        stage('build') {
            steps {
                sh  '''
                  cd app_python
                  pip install --no-cache-dir -r requirements.txt
                '''
            }
        }
        stage('test') {
            steps {
                sh '''
                  pip install pytest
                  pip install pytest-cov
                  pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
                '''
            }
        }
    }
}

