global:
   scrape_interval: 10s
   evaluation_interval: 10s

scrape_configs:
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"] 
  - job_name: "localhost"
    static_configs:
      - targets: ["localhost:9090"]